// @ts-nocheck
export const DEFAULT_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 12,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 3, y: 0, minW: 3, minH: 2 },
    {
      h: 2,
      i: 'WORKSPACE_ACTIVITY',
      moved: false,
      static: false,
      w: 6,
      x: 6,
      y: 0,
      minW: 6,
      minH: 2,
    },
    {
      h: 2,
      i: 'CONNECTIONS_STATUS_CHART',
      moved: false,
      static: false,
      w: 6,
      x: 3,
      y: 2,
      minW: 6,
      minH: 2,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 10,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 6,
      y: 0,
      minW: 3,
      minH: 2,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 3, y: 0, minW: 3, minH: 2 },
    {
      h: 2,
      i: 'WORKSPACE_ACTIVITY',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 0,
      minW: 6,
      minH: 2,
    },
    {
      h: 2,
      i: 'CONNECTIONS_STATUS_CHART',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 2,
      minW: 6,
      minH: 2,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 6,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 3, y: 0, minW: 3, minH: 2 },
    {
      h: 2,
      i: 'WORKSPACE_ACTIVITY',
      moved: false,
      static: false,
      w: 6,
      x: 6,
      y: 0,
      minW: 6,
      minH: 2,
    },
    {
      h: 2,
      i: 'CONNECTIONS_STATUS_CHART',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 2,
      minW: 6,
      minH: 2,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 4,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 2, minW: 2, minH: 2 },
    {
      h: 2,
      i: 'WORKSPACE_ACTIVITY',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 4,
      minW: 4,
      minH: 2,
    },
    {
      h: 2,
      i: 'CONNECTIONS_STATUS_CHART',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 6,
      minW: 4,
      minH: 2,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 2, minW: 2, minH: 2 },
    {
      h: 2,
      i: 'WORKSPACE_ACTIVITY',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 4,
      minW: 2,
      minH: 2,
    },
    {
      h: 2,
      i: 'CONNECTIONS_STATUS_CHART',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 6,
      minW: 2,
      minH: 2,
    },
  ],
};

export const LOCAL_PROVIDER_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 12,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 10,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 6,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 4,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 3,
      minH: 2,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2.565,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2,
    },
  ],
};

export const OVERVIEW_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 12,
      minH: 2.565,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
      minW: 10,
      minH: 2.565,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 6,
      minH: 2.565,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 4,
      minH: 2.565,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
      minW: 2,
      minH: 2.565,
    },
  ],
};
